spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    username: user
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: true
  flyway:
    baseline-on-migrate: true
