spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/eshop
    username: user
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true