spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/eshop
    username: user
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        use-sql-comments: true
        format_sql: true
    open-in-view: true
  flyway:
    baseline-on-migrate: true